---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: TransitGateway
metadata:
  name: $TGW_NAME 
spec:
  description: $TGW_DESCRIPTION
  options:
    dnsSupport: $DNS_SUPPORT
    defaultRouteTableAssociation: $ROUTE_TABLE_ASSOCIATION
    transitGatewayCIDRBlocks:
    - $CIDR_BLOCK
  tags:
    - key: $TAG_KEY
      value: $TAG_VALUE